#!/bin/sh
#
# Simple script to configure the
HOOK=$1
#HOOK=`pwd`

if [ "$2" = "" ]
then
  echo 'No directory provided, assuming the parent directory holds puppet repos.'
  LOCATION=`dirname pwd`
else
  LOCATION=$2
fi

echo "Installing hook to all directories underneath ${LOCATION}"
cd ${LOCATION}
for DIR in `ls -d */`
do
  cd ${LOCATION}
  echo "Adding hook to directory ${DIR}"
  #cd ${DIR}
  cp ${HOOK}/pre-commit .git/hooks/pre-commit
  chmod +x .git/hooks/pre-commit
  #ln -sf ${HOOK}/pre-commit .git/hooks/pre-commit
done
cd ${HOOK}

#echo 'Setting the executable bit on the hook.'
#chmod +x pre-commit

echo 'Installation complete.'
echo ''
