#!/bin/sh
#
# Simple script to add Puppet pre-commit git hook to all repos under a directory
ALL_PUPPET_MODULES=false
HOOK=$1

if [ "$2" = "" ]
then
  echo 'No directory provided, assuming the parent directory holds puppet repos.'
  LOCATION=`dirname pwd`
else
  LOCATION=$2
fi

if [ "$ALL_PUPPET_MODULES" = true ] ; then
  echo "Installing hook to all directories underneath ${LOCATION}"
  for DIR in `ls -d */`
  do
    echo "Adding hook to directory ${DIR}"
    cp --remove-destination ${HOOK}/pre-commit ${DIR}.git/hooks/pre-commit
  done
fi

echo "Installing hook underneath ${LOCATION}"
cp --remove-destination ${HOOK}/pre-commit ${LOCATION}.git/hooks/pre-commit

echo 'Installation complete.'
echo ''
