#!/bin/sh
#
# Simple script to add Puppet pre-commit git hook to all repos under a directory
HOOK=$1

if [ "$2" = "" ]
then
  echo 'No directory provided, assuming the parent directory holds puppet repos.'
  LOCATION=`dirname pwd`
else
  LOCATION=$2
fi

echo "Installing hook to all directories underneath ${LOCATION}"
cd ${LOCATION}
for DIR in `ls -d */`
do
  echo "Adding hook to directory ${DIR}"
  cp --remove-destination ${HOOK}/pre-commit ${DIR}.git/hooks/pre-commit
done
cd ${HOOK}

echo 'Installation complete.'
echo ''
